In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as ptl

In [3]:
df=pd.read_csv("../data/raw/train.csv")

In [4]:
df.sample(5)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
5161,5162,CA-2015-111192,30/07/2015,05/08/2015,Standard Class,TS-21430,Tom Stivers,Corporate,United States,Seattle,Washington,98103.0,West,FUR-BO-10002916,Furniture,Bookcases,"Rush Hierlooms Collection 1"" Thick Stackable B...",1367.840
629,630,CA-2018-133431,17/12/2018,21/12/2018,Standard Class,LC-17140,Logan Currie,Consumer,United States,San Francisco,California,94122.0,West,OFF-PA-10002615,Office Supplies,Paper,"Ampad Gold Fibre Wirebound Steno Books, 6"" x 9...",13.230
2461,2462,CA-2016-142419,11/07/2016,13/07/2016,Second Class,SC-20380,Shahid Collister,Consumer,United States,Seattle,Washington,98115.0,West,OFF-BI-10001597,Office Supplies,Binders,"Wilson Jones Ledger-Size, Piano-Hinge Binder, ...",98.352
7010,7011,US-2015-135881,23/05/2015,27/05/2015,Standard Class,GT-14710,Greg Tran,Consumer,United States,New York City,New York,10035.0,East,OFF-BI-10000829,Office Supplies,Binders,Avery Non-Stick Binders,17.960
9655,9656,CA-2015-156160,22/09/2015,29/09/2015,Standard Class,AS-10090,Adam Shillingsburg,Consumer,United States,New York City,New York,10035.0,East,FUR-FU-10001876,Furniture,Furnishings,"Computer Room Manger, 14""",97.440

### Issue with dataset
1. Dirty Data
- Postal code column have missing values
- The format of date and time is in string

In [5]:
df.describe()

            Row ID   Postal Code         Sales
count  9800.000000   9789.000000   9800.000000
mean   4900.500000  55273.322403    230.769059
std    2829.160653  32041.223413    626.651875
min       1.000000   1040.000000      0.444000
25%    2450.750000  23223.000000     17.248000
50%    4900.500000  58103.000000     54.490000
75%    7350.250000  90008.000000    210.605000
max    9800.000000  99301.000000  22638.480000

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9800 entries, 0 to 9799
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9800 non-null   int64
 1   Order ID       9800 non-null   str
 2   Order Date     9800 non-null   str
 3   Ship Date      9800 non-null   str
 4   Ship Mode      9800 non-null   str
 5   Customer ID    9800 non-null   str
 6   Customer Name  9800 non-null   str
 7   Segment        9800 non-null   str
 8   Country        9800 non-null   str
 9   City           9800 non-null   str
 10  State          9800 non-null   str
 11  Postal Code    9789 non-null   float64
 12  Region         9800 non-null   str
 13  Product ID     9800 non-null   str
 14  Category       9800 non-null   str
 15  Sub-Category   9800 non-null   str
 16  Product Name   9800 non-null   str
 17  Sales          9800 non-null   float64
dtypes: float64(2), int64(1), str(15)
memory usage: 3.1 MB

In [7]:
df.isna().sum()

Row ID            0
Order ID          0
Order Date        0
Ship Date         0
Ship Mode         0
Customer ID       0
Customer Name     0
Segment           0
Country           0
City              0
State             0
Postal Code      11
Region            0
Product ID        0
Category          0
Sub-Category      0
Product Name      0
Sales             0
dtype: int64

In [8]:
df['Postal Code']=df['Postal Code'].astype('Int64')

In [9]:
df.isna().sum()

Row ID            0
Order ID          0
Order Date        0
Ship Date         0
Ship Mode         0
Customer ID       0
Customer Name     0
Segment           0
Country           0
City              0
State             0
Postal Code      11
Region            0
Product ID        0
Category          0
Sub-Category      0
Product Name      0
Sales             0
dtype: int64

### Change into date format

In [10]:
df['Order Date']=pd.to_datetime(df['Order Date'], format='%d/%m/%Y')
df['Ship Date']=pd.to_datetime(df['Ship Date'], format='%d/%m/%Y')

### Creating columns based on time

In [11]:
df['Year']=df['Order Date'].dt.year
df['Month']=df['Order Date'].dt.month
df['Month_Name']=df['Order Date'].dt.month_name()
df['Quarter']=df['Order Date'].dt.quarter
df['Year_Month']=df['Order Date'].dt.to_period('M')
df['Day']=df['Order Date'].dt.day
df['Day_of_Week']=df['Order Date'].dt.day_name()

In [12]:
df.duplicated().sum()

np.int64(0)

### Unique value

In [13]:
df['Ship Mode'].unique()

<ArrowStringArray>
['Second Class', 'Standard Class', 'First Class', 'Same Day']
Length: 4, dtype: str

In [14]:
df['Segment'].unique()

<ArrowStringArray>
['Consumer', 'Corporate', 'Home Office']
Length: 3, dtype: str

In [15]:
df['Region'].unique()

<ArrowStringArray>
['South', 'West', 'Central', 'East']
Length: 4, dtype: str

In [16]:
df['Category'].unique()

<ArrowStringArray>
['Furniture', 'Office Supplies', 'Technology']
Length: 3, dtype: str

In [17]:
df['Sub-Category'].unique()

<ArrowStringArray>
[  'Bookcases',      'Chairs',      'Labels',      'Tables',     'Storage',
 'Furnishings',         'Art',      'Phones',     'Binders',  'Appliances',
       'Paper', 'Accessories',   'Envelopes',   'Fasteners',    'Supplies',
    'Machines',     'Copiers']
Length: 17, dtype: str

In [18]:
# Remove extra Whitespace
text_columns = [
    "Order ID",
    "Ship Mode",
    "Customer ID",
    "Customer Name",
    "Segment",
    "Country",
    "City",
    "State",
    "Region",
    "Product ID",
    "Category",
    "Sub-Category",
    "Product Name"
]

for col in text_columns:
    df[col] = df[col].str.strip()

In [19]:
df['Sales'].describe()

count     9800.000000
mean       230.769059
std        626.651875
min          0.444000
25%         17.248000
50%         54.490000
75%        210.605000
max      22638.480000
Name: Sales, dtype: float64

In [21]:
df[df["Sales"] <= 0]

Empty DataFrame
Columns: [Row ID, Order ID, Order Date, Ship Date, Ship Mode, Customer ID, Customer Name, Segment, Country, City, State, Postal Code, Region, Product ID, Category, Sub-Category, Product Name, Sales, Year, Month, Month_Name, Quarter, Year_Month, Day, Day_of_Week]
Index: []

[0 rows x 25 columns]

In [22]:
df["Sales"].isna().sum()

np.int64(0)

In [23]:
df["Shipping_Days"] = (df["Ship Date"] - df["Order Date"]).dt.days

In [24]:
df["Shipping_Days"].describe()

count    9800.000000
mean        3.961122
std         1.749614
min         0.000000
25%         3.000000
50%         4.000000
75%         5.000000
max         7.000000
Name: Shipping_Days, dtype: float64

In [25]:
df.groupby("Ship Mode")["Shipping_Days"].mean().sort_values()

Ship Mode
Same Day          0.044610
First Class       2.179214
Second Class      3.249211
Standard Class    5.008363
Name: Shipping_Days, dtype: float64

In [26]:
df.to_csv("../data/processed/retail_cleaned.csv",index=False)